version: "3.8"

services:
  database:
    container_name: bookmark_db
    image: postgres:15.5-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

    networks:
      - bookmark

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - api_server:/app/
    depends_on:
      - database

    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=${PORT}
    networks:
      - bookmark

volumes:
  api_server:
  db:


networks:
  bookmark:
    driver: bridge
