version: "3.8"

services:
  database:
    container_name: bookmark_db
    image: postgres:15.5-alpine
    env_file:
      - ./.env_docker
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U holyraven -d bookmark_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env_docker
    container_name: bookmark_api
    depends_on:
      - database
    ports:
      - '8000:8000'
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=database
      - DB_USER=holyraven
      - DB_PASSWORD=holyraven
      - DB_NAME=bookmark_db
      - DB_PORT=5432 # Ubah dari 5435 menjadi 5432
      - PORT=${PORT}

volumes:
  db:
